"""Create the v2.4 report figure notebook.

The notebook generated by this script renders Figure 3 through Figure 31 from
the formal report outline in ``v2.4 Report.docx``.  It uses local CSV result
files when available and falls back to small illustrative examples for diagram
style figures or missing experiment outputs.
"""

from __future__ import annotations

import json
from pathlib import Path
from textwrap import dedent


NOTEBOOK_PATH = Path("notebooks/experiments/v24_report_figures.ipynb")


SETUP_CODE = r'''
from pathlib import Path
import math
import textwrap
import warnings

import numpy as np
import pandas as pd
import yaml

import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch, Rectangle
try:
    from IPython.display import display
except Exception:
    display = None

warnings.filterwarnings("ignore", category=FutureWarning)

def find_project_root(start=None):
    start = Path.cwd() if start is None else Path(start)
    for candidate in [start, *start.parents]:
        if (candidate / "app").exists() and (candidate / "backtesting_results").exists():
            return candidate
    return start

ROOT = find_project_root()
OUT_DIR = ROOT / "outputs" / "report_figures" / "v2_4"
OUT_DIR.mkdir(parents=True, exist_ok=True)

plt.rcParams.update({
    "figure.dpi": 140,
    "savefig.dpi": 220,
    "font.size": 10,
    "axes.titlesize": 13,
    "axes.labelsize": 10,
    "axes.grid": True,
    "grid.alpha": 0.25,
    "axes.spines.top": False,
    "axes.spines.right": False,
})

COLORS = {
    "v2.1": "#8A8F98",
    "v2.2": "#4E79A7",
    "v2.3": "#F28E2B",
    "v2.4": "#59A14F",
    "ridge": "#59A14F",
    "rule": "#F28E2B",
    "accent": "#E15759",
    "muted": "#BAB0AC",
    "ink": "#2F3A45",
}

DATA_PATHS = {
    "trajectory_v23_v24": "backtesting_results/trajectory_v23_v24_3day/trajectory_detail_v23_v24_offline.csv",
    "termination_event_v23_v24": "backtesting_results/trajectory_v23_v24_3day/termination_event_detail_v23_v24_offline.csv",
    "summary_overall": "backtesting_results/trajectory_v23_v24_3day/summary_overall.csv",
    "summary_year_stage": "backtesting_results/trajectory_v23_v24_3day/summary_year_stage.csv",
    "zero_day_v22_v23": "backtesting_results/zero_day_error_v22_v23_3day/zero_day_error_detail_v22_v23.csv",
    "rule_summary": "backtesting_results/zero_day_error_v22_v23_3day/termination_rules/termination_rule_summary_overall.csv",
    "baseline_vs_learned": "backtesting_results/trajectory_curve_features_learned_termination/baseline_vs_learned_termination_detail_v23.csv",
    "fair_threshold": "backtesting_results/trajectory_curve_features_learned_termination/fair_threshold_comparison_summary_v23.csv",
    "alpha_grid": "backtesting_results/trajectory_curve_features_learned_termination/ridge_alpha_theta_grid_overall_v23.csv",
    "ablation_summary": "backtesting_results/trajectory_curve_features_learned_termination/ridge_feature_ablation_summary_v23.csv",
    "ablation_detail": "backtesting_results/trajectory_curve_features_learned_termination/ridge_feature_ablation_detail_v23.csv",
    "offline_v24_model_audit": "backtesting_results/trajectory_v23_v24_3day/offline_v24_model_audit.csv",
}

FIGURE_CAPTIONS = {
    1: "WeevilTrak Prediction Task Diagram",
    2: "Example v2.3 Failure Trajectory",
    3: "Version Evolution Timeline",
    4: "v2.4 End-to-End Architecture Diagram",
    5: "Zero-day Error Concept Diagram",
    6: "v2.2 vs v2.3 Zero-day Error Distribution",
    7: "Learned Termination Decision Flowchart",
    8: "Trajectory Signal, Lag and Slope Illustration",
    9: "Rolling Linear and Spline Crossing Illustration",
    10: "Feature Ablation Results",
    11: "Training Pipeline for v2.4",
    12: "Online Inference Flow Diagram",
    13: "Walk-forward Validation Split by Year",
    14: "Backtesting Framework Overview",
    15: "Threshold Sweep for Learned Ridge",
    16: "Ridge Alpha Grid Search Results",
    17: "Feature Group Ablation Impact on Decision RMSE",
    18: "Reached Rate Comparison",
    19: "Decision MAE and RMSE Comparison",
    20: "Adjusted Business-Date Error Distribution for Learned Ridge",
    21: "Decision Error Distribution",
    22: "v2.3 vs v2.4 Absolute Error Distribution",
    23: "Within 3d and Within 5d Accuracy Comparison",
    24: "Post-event Positive Rate Comparison",
    25: "Bounce-back Case Study Trajectories",
    26: "Stage-level MAE Improvement",
    27: "Year-level MAE / RMSE Comparison",
    28: "Location-level Error Map or Latitude-band Error Plot",
    29: "Representative Trajectory Case Studies",
    30: "Production Runtime Decision Tree",
    31: "Proposed Production Monitoring Dashboard Layout",
}

TABLE_CAPTIONS = {
    1: "Executive Summary Metrics",
    2: "Model Evolution Summary",
    3: "v2.4 Output Columns and Definitions",
    4: "Primary LightGBM Feature List",
    5: "Rule A vs Rule B Comparison",
    6: "Learned Termination Configuration",
    7: "Static and Contextual Termination Features",
    8: "v2.4 Prediction Output Schema",
    9: "v2.4 Unit Test Inventory",
    10: "Evaluation Metrics Definition Table",
    11: "Rule-based Termination Baseline Results",
    12: "Final Learned Termination Model Selection Summary",
    13: "v2.3 vs v2.4 Overall Forecast Accuracy",
    14: "Stage-level v2.3 vs v2.4 Performance Summary",
    15: "Core Implementation Functions and Responsibilities",
    16: "Risk Register and Mitigation Plan",
}

def read_data(key, parse_dates=None):
    path = ROOT / DATA_PATHS[key]
    if not path.exists():
        print(f"[fallback] Missing {path.relative_to(ROOT)}")
        return pd.DataFrame()
    df = pd.read_csv(path)
    for col in parse_dates or []:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce")
    return df

def read_config(version="v2.4"):
    path = ROOT / "app" / "config" / f"weeviltrak_{version}.yml"
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)

def clean_label(value):
    return str(value).replace("_", " ").replace("Learned Ridge threshold", "Learned Ridge").replace("Rule A signal<=0", "Rule A")

def save_and_show(fig, number, slug):
    path = OUT_DIR / f"figure_{number:02d}_{slug}.png"
    fig.savefig(path, bbox_inches="tight")
    plt.show()
    print(f"Saved: {path.relative_to(ROOT)}")
    return path

def save_table(df, number, slug):
    csv_path = OUT_DIR / f"table_{number:02d}_{slug}.csv"
    png_path = OUT_DIR / f"table_{number:02d}_{slug}.png"
    df.to_csv(csv_path, index=False)

    fig_w = min(max(8, 1.9 * len(df.columns)), 18)
    fig_h = min(max(2.4, 0.45 * (len(df) + 2)), 12)
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    ax.axis("off")
    wrapped = df.copy()
    for col in wrapped.columns:
        wrapped[col] = wrapped[col].map(lambda x: textwrap.fill(str(x), width=34))
    table = ax.table(
        cellText=wrapped.values,
        colLabels=wrapped.columns,
        loc="center",
        cellLoc="left",
        colLoc="left",
    )
    table.auto_set_font_size(False)
    table.set_fontsize(8.5)
    table.scale(1, 1.35)
    for (row, col), cell in table.get_celld().items():
        cell.set_edgecolor("#D0D7DE")
        if row == 0:
            cell.set_facecolor("#D9EAF7")
            cell.set_text_props(weight="bold", color=COLORS["ink"])
        elif row % 2 == 0:
            cell.set_facecolor("#F7F9FB")
    ax.set_title(f"Table {number}. {TABLE_CAPTIONS[number]}", loc="left", weight="bold", pad=12)
    fig.savefig(png_path, bbox_inches="tight")
    plt.show()
    print(f"Saved: {csv_path.relative_to(ROOT)}")
    print(f"Saved: {png_path.relative_to(ROOT)}")
    try:
        if display is None:
            raise NameError("display unavailable")
        display(df)
    except NameError:
        print(df.to_string(index=False))
    return df

def box(ax, xy, text, w=1.8, h=0.55, color="#EAF2F8", edge="#2F3A45", fontsize=9):
    x, y = xy
    patch = FancyBboxPatch(
        (x, y), w, h,
        boxstyle="round,pad=0.04,rounding_size=0.06",
        linewidth=1.2,
        facecolor=color,
        edgecolor=edge,
    )
    ax.add_patch(patch)
    ax.text(x + w/2, y + h/2, text, ha="center", va="center", fontsize=fontsize, wrap=True)
    return patch

def arrow(ax, start, end, color="#2F3A45", lw=1.5):
    ax.add_patch(FancyArrowPatch(start, end, arrowstyle="-|>", mutation_scale=14, linewidth=lw, color=color))

def bar_labels(ax, fmt="{:.2f}", rotation=0):
    for container in ax.containers:
        try:
            ax.bar_label(container, fmt=fmt, fontsize=8, rotation=rotation, padding=2)
        except Exception:
            pass

def grouped_bar(ax, labels, series, ylabel="", title=""):
    x = np.arange(len(labels))
    width = 0.8 / max(len(series), 1)
    for i, (name, values) in enumerate(series.items()):
        offset = (i - (len(series)-1)/2) * width
        ax.bar(x + offset, values, width, label=name, color=COLORS.get(name, None))
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=20, ha="right")
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.legend(frameon=False)

def sample_signal_frame():
    dates = pd.date_range("2025-04-01", periods=12, freq="3D")
    signal = np.array([25, 21, 18, 14, 11, 8, 5, 2, -0.4, 0.8, -0.8, -1.2])
    return pd.DataFrame({"prediction_date": dates, "signal": signal})

def draw_pipeline(ax, labels, colors=None):
    ax.axis("off")
    n = len(labels)
    xs = np.linspace(0.05, 0.82, n)
    for i, (x, label) in enumerate(zip(xs, labels)):
        color = colors[i] if colors else "#EAF2F8"
        box(ax, (x, 0.45), label, w=0.13, h=0.18, color=color, fontsize=8)
        if i < n - 1:
            arrow(ax, (x + 0.13, 0.54), (xs[i+1], 0.54))
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)

def table_1():
    df = read_data("summary_overall")
    metrics = [
        ("MAE", "mae_stage_date_error"),
        ("RMSE", "rmse_stage_date_error"),
        ("P90 abs error", "p90_abs_stage_date_error"),
        ("Within 3d rate", "within_3d_rate"),
        ("Within 5d rate", "within_5d_rate"),
        ("Post-event positive rate", "post_event_positive_rate"),
        ("Termination active row rate", "termination_reached_rate"),
    ]
    if df.empty:
        df = pd.DataFrame({
            "model_version": ["v2.3", "v2.4"],
            "mae_stage_date_error": [11.65, 6.66],
            "rmse_stage_date_error": [16.31, 9.69],
            "p90_abs_stage_date_error": [29.0, 16.0],
            "within_3d_rate": [0.268, 0.411],
            "within_5d_rate": [0.403, 0.585],
            "post_event_positive_rate": [0.084, 0.050],
            "termination_reached_rate": [0.000, 0.373],
        })
    rows = []
    by_ver = df.set_index("model_version")
    for label, col in metrics:
        v23 = by_ver[col].get("v2.3", np.nan)
        v24 = by_ver[col].get("v2.4", np.nan)
        rows.append({
            "Metric": label,
            "v2.3": v23,
            "v2.4": v24,
            "Delta v2.4 - v2.3": v24 - v23,
        })
    event = read_data("termination_event_v23_v24")
    if not event.empty and "termination_reached" in event.columns:
        event_rate = (
            event.groupby("model_version")["termination_reached"].mean().to_dict()
        )
        v23 = event_rate.get("v2.3", np.nan)
        v24 = event_rate.get("v2.4", np.nan)
        rows.append(
            {
                "Metric": "Termination reached trajectory rate",
                "v2.3": v23,
                "v2.4": v24,
                "Delta v2.4 - v2.3": v24 - v23,
            }
        )
    return pd.DataFrame(rows), "executive_summary_metrics"

def table_2():
    return pd.DataFrame([
        ["v2.1", "Random Forest", "days_to_event", "Legacy baseline", "No signed post-event semantics"],
        ["v2.2", "LightGBM", "signed_days_to_event", "Signed target, monotonic constraint, post-event zero rows", "Termination remained rule-based"],
        ["v2.3", "LightGBM", "signed_days_to_event", "DOY, CDD, 14-day rolling feature upgrade", "Zero-day decision still heuristic"],
        ["v2.4", "LightGBM + Ridge termination", "signed_days_to_event + learned calibration", "Learned termination layer", "Requires monitoring for early termination"],
    ], columns=["Version", "Model", "Target", "Key change", "Main limitation"]), "model_evolution_summary"

def table_3():
    rows = [
        ("raw_signed_days", "Direct LightGBM signed-days output before clipping."),
        ("predicted_days", "Business-facing adjusted remaining days: max(learned_days_remaining - threshold, 0) when learned termination is active."),
        ("predicted_stage_date", "Business-facing predicted stage date from the adjusted remaining-days curve."),
        ("base_predicted_days", "Original predicted_days before learned termination overwrite."),
        ("base_predicted_stage_date", "Original predicted_stage_date before learned termination overwrite."),
        ("termination_rule", "Name of the applied termination rule."),
        ("termination_threshold", "Learned Ridge offset used to calibrate the business zero boundary."),
        ("learned_days_remaining", "Raw Ridge-estimated latent days remaining, preserved for diagnostics."),
        ("termination_adjusted_days_remaining", "Business adjusted remaining days after subtracting the threshold and clipping at zero."),
        ("termination_reached", "Boolean flag indicating adjusted remaining days reached zero."),
        ("termination_decision_date", "Prediction date on which adjusted remaining days reached zero."),
        ("termination_estimated_stage_date", "Business estimated stage date from adjusted remaining days; equals decision date at termination."),
    ]
    return pd.DataFrame(rows, columns=["Column", "Definition"]), "v24_output_columns"

def table_4():
    config = read_config("v2.4")
    constraints = config.get("model_parameters", {}).get("monotone_constraints_by_feature", {})
    rows = []
    for feature in config.get("features", []):
        rows.append({
            "Feature": feature,
            "Role": "Primary LightGBM input",
            "Monotonic constraint": constraints.get(feature, 0),
        })
    return pd.DataFrame(rows), "primary_lgbm_feature_list"

def table_5():
    rows = [
        ["Rule A", "First raw_signed_days <= 0", "Simple and auditable", "Can trigger too early when trajectory briefly crosses zero"],
        ["Rule B", "Confirmed/interpolated threshold crossing", "Reduces noisy single-day decisions", "Still hand-tuned and threshold-sensitive"],
        ["v2.4 learned Ridge", "business_remaining = max(learned_days_remaining - 4.5, 0)", "Uses trajectory shape, lag, slope and crossing features", "Requires model validation and monitoring"],
    ]
    return pd.DataFrame(rows, columns=["Rule", "Decision logic", "Strength", "Limitation"]), "rule_a_vs_rule_b"

def table_6():
    tm = read_config("v2.4").get("termination_model", {})
    rows = [{"Parameter": k, "Value": v} for k, v in tm.items()]
    return pd.DataFrame(rows), "learned_termination_configuration"

def table_7():
    rows = [
        ["stage", "Categorical", "Lifecycle stage context"],
        ["prediction_day_of_year", "Numeric", "Seasonal timing"],
        ["feature_latitude", "Numeric", "Spatial context"],
        ["feature_longitude", "Numeric", "Spatial context"],
        ["raw_signed_days / predicted_days", "Numeric", "Base model signal"],
        ["signal_lag1 / lag2 / lag3", "Numeric", "Visible trajectory history"],
        ["slope_1 / slope_2 / slope_3", "Numeric", "Recent trajectory direction"],
        ["recent mean/std/min/max", "Numeric", "Recent trajectory shape"],
        ["rolling crossing features", "Numeric", "Estimated zero or -0.5 crossing timing"],
    ]
    return pd.DataFrame(rows, columns=["Feature group", "Type", "Purpose"]), "termination_static_contextual_features"

def table_8():
    rows = [
        ("location_id", "Location identifier"),
        ("stage_id", "Lifecycle stage identifier"),
        ("latitude / longitude", "Prediction location coordinates"),
        ("prediction_date", "Date on which prediction is issued"),
        ("raw_signed_days", "Signed primary model output"),
        ("predicted_days", "Final business remaining-days output"),
        ("predicted_stage_date", "Final business stage-date output"),
        ("termination diagnostics", "Rule, threshold, learned days, reached flag and decision date"),
        ("base prediction diagnostics", "Pre-termination predicted days and stage date"),
    ]
    return pd.DataFrame(rows, columns=["Output field", "Definition"]), "v24_prediction_output_schema"

def table_9():
    rows = [
        ["tests/unit/models/test_learned_termination.py", "v2.4 config, feature frame, Ridge training and overwrite behavior"],
        ["tests/unit/pipeline/test_zero_day_error.py", "Zero-day error detail and summary logic"],
        ["tests/unit/models/test_lightgbm_monotonic_constraints.py", "LightGBM monotonic constraint behavior"],
        ["tests/unit/services/test_post_event_zero_training.py", "Post-event zero-row training support"],
        ["tests/unit/services/test_v23_feature_engineering.py", "DOY, CDD and 14-day rolling features"],
        ["tests/unit/pipeline/test_signed_target_outputs.py", "raw_signed_days and clipped predicted_days behavior"],
        ["tests/integration/test_backtesting_event_window_validation.py", "Event-centered validation helper behavior"],
    ]
    return pd.DataFrame(rows, columns=["Test file", "Coverage"]), "unit_test_inventory"

def table_10():
    rows = [
        ["MAE", "Mean absolute stage-date error", "Lower is better"],
        ["RMSE", "Root mean squared stage-date error", "Lower is better; penalizes large misses"],
        ["P90 abs error", "90th percentile absolute error", "Tail-risk measure"],
        ["Within 3d / 5d rate", "Share of predictions within tolerance window", "Higher is better"],
        ["Zero-day error", "First zero decision date minus actual stage date", "Negative early, positive late"],
        ["Post-event positive rate", "Post-event rows where predicted_days > 0", "Lower is better"],
        ["Bounce-up rate", "Consecutive trajectory steps where predicted_days increases", "Lower is better"],
        ["Termination reached rate", "Share of rows or trajectories where learned termination triggers", "Monitor for drift"],
    ]
    return pd.DataFrame(rows, columns=["Metric", "Definition", "Interpretation"]), "evaluation_metrics_definitions"

def table_11():
    df = read_data("rule_summary")
    if df.empty:
        df = pd.DataFrame({
            "termination_rule": ["rule_A", "rule_B"],
            "termination_theta": [0.0, -0.5],
            "model_version": ["v2.3", "v2.3"],
            "termination_reached_rate": [0.90, 0.95],
            "mean_abs_termination_error_days": [6.2, 5.8],
            "rmse_termination_error_days": [9.1, 8.7],
        })
    keep = [c for c in ["termination_rule", "termination_theta", "model_version", "termination_reached_rate", "mean_abs_termination_error_days", "rmse_termination_error_days", "early_rate", "late_rate"] if c in df.columns]
    out = df[keep].head(12).copy()
    return out, "rule_based_termination_baseline_results"

def table_12():
    df = read_data("fair_threshold")
    if df.empty:
        df = pd.DataFrame({
            "method": ["Learned Ridge threshold"],
            "theta": [4.5],
            "reached_rate": [0.996],
            "decision_mae": [4.40],
            "decision_rmse": [6.47],
            "decision_bias": [-0.26],
        })
    keep = [c for c in ["method", "theta", "reached_rate", "decision_mae", "decision_rmse", "decision_bias", "early_rate_among_reached", "late_rate_among_reached"] if c in df.columns]
    return df[keep].copy(), "final_learned_termination_selection"

def table_13():
    df = read_data("summary_overall")
    if df.empty:
        df = pd.DataFrame({"model_version":["v2.3","v2.4"],"mae_stage_date_error":[11.65,6.66],"rmse_stage_date_error":[16.31,9.69],"within_3d_rate":[0.268,0.411],"within_5d_rate":[0.403,0.585]})
    keep = [c for c in ["model_version", "mae_stage_date_error", "rmse_stage_date_error", "p90_abs_stage_date_error", "within_3d_rate", "within_5d_rate", "post_event_positive_rate", "termination_reached_rate"] if c in df.columns]
    return df[keep].copy(), "v23_v24_overall_forecast_accuracy"

def table_14():
    df = read_data("summary_year_stage")
    if df.empty:
        df = pd.DataFrame({"model_version":["v2.3","v2.4"]*3,"stage_id":[1,1,2,2,3,3],"mae_stage_date_error":[12,7,10,6,13,8],"rmse_stage_date_error":[17,10,15,9,18,11]})
    metric_cols = [c for c in ["mae_stage_date_error", "rmse_stage_date_error", "within_5d_rate", "post_event_positive_rate"] if c in df.columns]
    out = df.groupby(["stage_id", "model_version"])[metric_cols].mean(numeric_only=True).reset_index()
    return out, "stage_level_v23_v24_performance_summary"

def table_15():
    rows = [
        ["app/pipeline/termination.py", "Build learned termination features, train Ridge model, apply termination rule"],
        ["app/pipeline/train_predict.py", "Train LightGBM and optional termination model; apply termination during prediction"],
        ["app/pipeline/backtesting.py", "Train cutoff-specific termination models and evaluate trajectory behavior"],
        ["app/pipeline/hindcast.py", "Apply configured termination model in historical prediction runs"],
        ["app/config/weeviltrak_v2.4.yml", "Versioned configuration for v2.4 model and termination layer"],
    ]
    return pd.DataFrame(rows, columns=["Component", "Responsibility"]), "core_implementation_functions"

def table_16():
    rows = [
        ["Premature termination", "Model predicts zero before actual event", "Track early-rate and decision bias; threshold sweep"],
        ["Late/non-reached termination", "Model fails to reach zero near event", "Monitor reached rate and post-event positive rate"],
        ["Regional drift", "Performance differs by geography", "Latitude-band and location-level summaries"],
        ["Stage-specific degradation", "One lifecycle stage worsens", "Stage-level MAE/RMSE and trigger-rate monitoring"],
        ["Base-model dependency", "Bad LightGBM trajectory weakens termination layer", "Preserve raw/base predictions for audit and fallback"],
        ["Data quality gaps", "Weather or observation noise affects labels", "Run data completeness checks and outlier review"],
    ]
    return pd.DataFrame(rows, columns=["Risk", "Description", "Mitigation"]), "risk_register_mitigation_plan"

def figure_1():
    fig, ax = plt.subplots(figsize=(10, 4))
    ax.axis("off")
    nodes = [
        ((0.04,0.62), "Weather\nGDD / CDD / humidity / precip", "#EAF2F8"),
        ((0.04,0.28), "Location + stage\nlat/lon/stage_id", "#EAF2F8"),
        ((0.30,0.45), "WeevilTrak\nfeature engineering", "#FFF2CC"),
        ((0.55,0.45), "Prediction model\nv2.4", "#E2F0D9"),
        ((0.78,0.58), "predicted_days", "#D9EAF7"),
        ((0.78,0.28), "predicted_stage_date", "#D9EAF7"),
    ]
    for xy, label, color in nodes:
        box(ax, xy, label, w=0.20, h=0.16, color=color)
    arrow(ax, (0.24,0.70), (0.30,0.55)); arrow(ax, (0.24,0.36), (0.30,0.50))
    arrow(ax, (0.50,0.53), (0.55,0.53)); arrow(ax, (0.75,0.53), (0.78,0.66)); arrow(ax, (0.75,0.49), (0.78,0.36))
    ax.set_title("Figure 1. WeevilTrak Prediction Task Diagram")
    ax.set_xlim(0,1); ax.set_ylim(0.1,0.9)
    return fig, "weeviltrak_prediction_task_diagram"

def figure_2():
    df = read_data("trajectory_v23_v24", parse_dates=["prediction_date", "actual_stage_date"])
    if not df.empty:
        v23 = df[df["model_version"] == "v2.3"].copy()
        keys = v23.groupby(["test_year", "location_id", "stage_id"])["post_event_positive"].sum().sort_values(ascending=False)
        if not keys.empty:
            year, loc, stage = keys.index[0]
            g = v23[(v23["test_year"] == year) & (v23["location_id"].astype(str) == str(loc)) & (v23["stage_id"] == stage)].sort_values("prediction_date")
        else:
            g = v23.sort_values("prediction_date").head(40)
    else:
        dates = pd.date_range("2025-04-01", periods=18, freq="3D")
        actual = pd.Timestamp("2025-05-10")
        g = pd.DataFrame({
            "prediction_date": dates,
            "predicted_days": np.maximum(30 - np.arange(len(dates))*2 + np.sin(np.arange(len(dates))*4)*3, 0),
            "actual_stage_date": actual,
        })
    fig, ax = plt.subplots(figsize=(9.5, 4.6))
    ax.plot(g["prediction_date"], g["predicted_days"], marker="o", color=COLORS["v2.3"], label="v2.3 predicted_days")
    actual = pd.to_datetime(g["actual_stage_date"].dropna().iloc[0])
    ax.axvline(actual, color=COLORS["accent"], lw=2, ls="--", label="actual stage date")
    post = g[g["prediction_date"] > actual]
    if not post.empty:
        ax.fill_between(post["prediction_date"], 0, post["predicted_days"], color=COLORS["accent"], alpha=0.15, label="post-event positive area")
    ax.annotate("bounce-back segment", xy=(g["prediction_date"].iloc[-4], g["predicted_days"].iloc[-4]), xytext=(g["prediction_date"].iloc[max(len(g)-9,0)], max(g["predicted_days"].max()*0.85, 5)),
                arrowprops=dict(arrowstyle="->", color=COLORS["accent"]), color=COLORS["accent"])
    ax.set_ylabel("predicted days")
    ax.set_title("Figure 2. Example v2.3 Failure Trajectory")
    ax.legend(frameon=False)
    return fig, "example_v23_failure_trajectory"

def figure_3():
    versions = [
        ("v2.1", "Random Forest\nbaseline", "days_to_event"),
        ("v2.2", "LightGBM\nsigned target", "post-event semantics"),
        ("v2.3", "Feature upgrade\nDOY + CDD + 14d", "cold-snap stability"),
        ("v2.4", "Learned Ridge\ntermination", "zero-day decision"),
    ]
    fig, ax = plt.subplots(figsize=(10, 3.4))
    ax.axis("off")
    xs = np.linspace(0.08, 0.82, len(versions))
    for i, (ver, title, note) in enumerate(versions):
        color = COLORS[ver]
        ax.scatter(xs[i], 0.62, s=520, color=color, zorder=3)
        ax.text(xs[i], 0.62, ver, color="white", weight="bold", ha="center", va="center")
        ax.text(xs[i], 0.38, title, ha="center", va="center", weight="bold")
        ax.text(xs[i], 0.18, note, ha="center", va="center", fontsize=9)
        if i < len(versions)-1:
            arrow(ax, (xs[i]+0.05, 0.62), (xs[i+1]-0.05, 0.62), lw=2)
    ax.set_title("Figure 3. Version Evolution Timeline")
    return fig, "version_evolution_timeline"

def figure_4():
    fig, ax = plt.subplots(figsize=(11, 4.5))
    ax.axis("off")
    boxes = [
        ((0.04, 0.62), "Weather\n10x10 km grid", "#EAF2F8"),
        ((0.04, 0.28), "Location + stage\nmetadata", "#EAF2F8"),
        ((0.27, 0.45), "Feature engineering\nGDD / CDD / rolling", "#FFF2CC"),
        ((0.50, 0.45), "LightGBM\nsigned-days model", "#FCE4D6"),
        ((0.70, 0.58), "raw_signed_days\nbase trajectory", "#F6E8FF"),
        ((0.70, 0.25), "Ridge learned\ntermination layer", "#E2F0D9"),
        ((0.89, 0.42), "Business output\npredicted_days\npredicted_stage_date", "#D9EAF7"),
    ]
    for xy, label, color in boxes:
        box(ax, xy, label, w=0.16, h=0.16, color=color, fontsize=9)
    arrow(ax, (0.20,0.70), (0.27,0.55)); arrow(ax, (0.20,0.36), (0.27,0.50))
    arrow(ax, (0.43,0.53), (0.50,0.53)); arrow(ax, (0.66,0.53), (0.70,0.66))
    arrow(ax, (0.78,0.58), (0.78,0.41)); arrow(ax, (0.86,0.33), (0.89,0.50))
    arrow(ax, (0.86,0.66), (0.89,0.56))
    ax.text(0.79, 0.49, "terminate?\nthreshold=4.5", ha="center", va="center", fontsize=8)
    ax.set_xlim(0,1.08); ax.set_ylim(0.1,0.9)
    ax.set_title("Figure 4. v2.4 End-to-End Architecture Diagram")
    return fig, "v24_end_to_end_architecture"

def figure_5():
    fig, ax = plt.subplots(figsize=(9, 4))
    actual = pd.Timestamp("2025-05-15")
    labels = ["early", "exact", "late", "not reached"]
    dates = [actual - pd.Timedelta(days=7), actual, actual + pd.Timedelta(days=7), pd.NaT]
    y = [1, 1, 1, 1]
    ax.axvline(actual, color=COLORS["accent"], lw=2, label="actual stage date")
    for i, (label, date) in enumerate(zip(labels, dates)):
        if pd.isna(date):
            ax.scatter(actual + pd.Timedelta(days=13), y[i], color=COLORS["muted"], s=100)
            ax.text(actual + pd.Timedelta(days=13), y[i]+0.08, "not reached", ha="center")
            continue
        color = COLORS["v2.4"] if label == "exact" else COLORS["v2.3"]
        ax.scatter(date, y[i], color=color, s=120)
        ax.text(date, y[i]+0.08, label, ha="center")
        ax.annotate("", xy=(date, y[i]-0.07), xytext=(actual, y[i]-0.07),
                    arrowprops=dict(arrowstyle="<->", color="#555"))
    ax.set_yticks([])
    ax.set_title("Figure 5. Zero-day Error Concept Diagram")
    ax.set_xlabel("first zero prediction date relative to actual stage date")
    ax.legend(frameon=False, loc="upper left")
    return fig, "zero_day_error_concept"

def figure_6():
    df = read_data("zero_day_v22_v23", parse_dates=["actual_stage_date", "first_zero_prediction_date"])
    if df.empty:
        df = pd.DataFrame({"model_version": ["v2.2"]*6 + ["v2.3"]*6, "zero_day_error_days": [-9,-5,-2,3,8,12,-6,-3,0,2,5,9]})
    df = df.dropna(subset=["zero_day_error_days"]).copy()
    fig, ax = plt.subplots(figsize=(9,4.5))
    versions = sorted(df["model_version"].unique())
    data = [df.loc[df["model_version"] == v, "zero_day_error_days"] for v in versions]
    ax.boxplot(data, labels=versions, patch_artist=True,
               boxprops=dict(facecolor="#D9EAF7"), medianprops=dict(color=COLORS["accent"], lw=2))
    ax.axhline(0, color="#333", lw=1)
    ax.set_ylabel("zero-day error days\nnegative=early, positive=late")
    ax.set_title("Figure 6. v2.2 vs v2.3 Zero-day Error Distribution")
    return fig, "v22_v23_zero_day_error_distribution"

def figure_7():
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.axis("off")
    nodes = [
        ((0.05,0.70), "Base prediction\ntrajectory", "#EAF2F8"),
        ((0.30,0.70), "Build lag / slope /\ncrossing features", "#FFF2CC"),
        ((0.55,0.70), "Ridge predicts\nlearned_days_remaining", "#E2F0D9"),
        ((0.55,0.38), "<= threshold\n4.5 days?", "#FCE4D6"),
        ((0.30,0.15), "No: keep\nbase output", "#F4F6F6"),
        ((0.78,0.15), "Yes: set\npredicted_days=0", "#D9EAD3"),
    ]
    for xy, label, color in nodes:
        box(ax, xy, label, w=0.18, h=0.16, color=color)
    arrow(ax, (0.23,0.78), (0.30,0.78)); arrow(ax, (0.48,0.78), (0.55,0.78))
    arrow(ax, (0.64,0.70), (0.64,0.54)); arrow(ax, (0.55,0.42), (0.46,0.31)); arrow(ax, (0.71,0.42), (0.80,0.31))
    ax.text(0.48,0.33,"False", fontsize=9); ax.text(0.74,0.33,"True", fontsize=9)
    ax.set_xlim(0,1); ax.set_ylim(0,1)
    ax.set_title("Figure 7. Learned Termination Decision Flowchart")
    return fig, "learned_termination_decision_flowchart"

def figure_8():
    df = sample_signal_frame()
    fig, ax = plt.subplots(figsize=(9,4.5))
    ax.plot(df["prediction_date"], df["signal"], marker="o", color=COLORS["v2.4"], label="termination_signal_days")
    i = 6
    for lag in [1,2,3]:
        ax.scatter(df.loc[i-lag, "prediction_date"], df.loc[i-lag, "signal"], s=80, label=f"lag{lag}")
        ax.annotate(f"lag{lag}", (df.loc[i-lag, "prediction_date"], df.loc[i-lag, "signal"]), xytext=(0,10), textcoords="offset points", ha="center")
    ax.annotate("slope_1", xy=(df.loc[i, "prediction_date"], df.loc[i, "signal"]), xytext=(df.loc[i-1, "prediction_date"], df.loc[i-1, "signal"]),
                arrowprops=dict(arrowstyle="->", color=COLORS["accent"], lw=2), color=COLORS["accent"])
    ax.axhline(0, color="#333", lw=1)
    ax.set_ylabel("days remaining signal")
    ax.set_title("Figure 8. Trajectory Signal, Lag and Slope Illustration")
    ax.legend(frameon=False, ncol=2)
    return fig, "trajectory_lag_slope_illustration"

def figure_9():
    df = sample_signal_frame()
    x = np.arange(len(df))
    y = df["signal"].to_numpy()
    coef = np.polyfit(x[-6:], y[-6:], 1)
    fit = np.polyval(coef, x)
    smooth = pd.Series(y).rolling(3, min_periods=1, center=True).mean().to_numpy()
    fig, ax = plt.subplots(figsize=(9,4.5))
    ax.plot(df["prediction_date"], y, marker="o", label="trajectory", color=COLORS["v2.4"])
    ax.plot(df["prediction_date"], fit, "--", label="rolling linear fit", color=COLORS["v2.3"])
    ax.plot(df["prediction_date"], smooth, ":", lw=2.5, label="smoothed spline proxy", color="#9467BD")
    ax.axhline(0, color="#333", lw=1, label="0 crossing")
    ax.axhline(-0.5, color=COLORS["accent"], lw=1, ls="--", label="-0.5 crossing")
    ax.set_ylabel("predicted signed days")
    ax.set_title("Figure 9. Rolling Linear and Spline Crossing Illustration")
    ax.legend(frameon=False)
    return fig, "rolling_crossing_illustration"

def figure_10():
    df = read_data("ablation_summary")
    if df.empty:
        df = pd.DataFrame({"ablation_name":["full_features","no_lags","no_crossings","no_location"],"decision_mae":[4.40,4.75,5.10,4.55]})
    df = df.copy().sort_values("decision_mae")
    fig, ax = plt.subplots(figsize=(9,4.5))
    ax.barh(df["ablation_name"].map(clean_label), df["decision_mae"], color=COLORS["v2.4"])
    ax.set_xlabel("decision MAE days")
    ax.set_title("Figure 10. Feature Ablation Results")
    return fig, "feature_ablation_results"

def figure_11():
    fig, ax = plt.subplots(figsize=(11,3.4))
    draw_pipeline(ax, ["training data", "LightGBM\ntrain", "base train\npredictions", "termination\nfeatures", "Ridge\ntrain", "save two\nmodels"],
                  ["#EAF2F8","#FCE4D6","#F6E8FF","#FFF2CC","#E2F0D9","#D9EAF7"])
    ax.set_title("Figure 11. Training Pipeline for v2.4")
    return fig, "v24_training_pipeline"

def figure_12():
    fig, ax = plt.subplots(figsize=(11,3.4))
    draw_pipeline(ax, ["test weather", "v2.4\nLightGBM", "raw signed\nprediction", "load Ridge\ntermination", "apply\nthreshold", "final\nbusiness output"],
                  ["#EAF2F8","#FCE4D6","#F6E8FF","#E2F0D9","#FFF2CC","#D9EAF7"])
    ax.set_title("Figure 12. Online Inference Flow Diagram")
    return fig, "online_inference_flow"

def figure_13():
    audit = read_data("offline_v24_model_audit")
    if audit.empty:
        audit = pd.DataFrame(
            {
                "validation_year": [2023, 2024, 2025],
                "training_years": ["[2022]", "[2022, 2023]", "[2022, 2023, 2024]"],
                "n_train_rows": [5076, 7760, 11126],
                "n_validation_rows": [2684, 3366, 4949],
            }
        )

    def parse_years(raw):
        if isinstance(raw, list):
            return [int(x) for x in raw]
        return [int(x) for x in str(raw).replace("[", "").replace("]", "").split(",") if x.strip()]

    audit = audit.copy()
    audit["validation_year"] = pd.to_numeric(audit["validation_year"], errors="coerce").astype(int)
    audit["training_year_list"] = audit["training_years"].map(parse_years)
    years = sorted(
        set(audit["validation_year"].tolist())
        | set(y for years_ in audit["training_year_list"] for y in years_)
    )

    fig, ax = plt.subplots(figsize=(9.5, 3.9))
    y_positions = np.arange(len(audit))
    cell_w = 0.82
    cell_h = 0.58
    for row_idx, (_, row) in enumerate(audit.sort_values("validation_year").iterrows()):
        validation_year = int(row["validation_year"])
        train_years = set(row["training_year_list"])
        for year in years:
            if year in train_years:
                color = "#D9EAF7"
                label = "Ridge training trajectory years"
            elif year == validation_year:
                color = COLORS["v2.4"]
                label = "validation year"
            else:
                color = "#F4F6F6"
                label = None
            ax.add_patch(
                Rectangle(
                    (year - cell_w / 2, row_idx - cell_h / 2),
                    cell_w,
                    cell_h,
                    facecolor=color,
                    edgecolor="#8091A5",
                    linewidth=1.0,
                )
            )
            if year in train_years or year == validation_year:
                ax.text(
                    year,
                    row_idx,
                    "train" if year in train_years else "test",
                    ha="center",
                    va="center",
                    fontsize=8.5,
                    color=COLORS["ink"] if year in train_years else "white",
                    weight="bold",
                )
        ax.text(
            max(years) + 0.75,
            row_idx,
            f"train rows={int(row.get('n_train_rows', 0)):,}\nvalid rows={int(row.get('n_validation_rows', 0)):,}",
            va="center",
            fontsize=8,
        )

    legend_handles = [
        Rectangle((0, 0), 1, 1, facecolor="#D9EAF7", edgecolor="#8091A5", label="Ridge training trajectory years"),
        Rectangle((0, 0), 1, 1, facecolor=COLORS["v2.4"], edgecolor="#8091A5", label="validation year"),
    ]
    ax.legend(handles=legend_handles, frameon=False, loc="upper center", bbox_to_anchor=(0.5, 1.18), ncol=2)
    ax.set_yticks(y_positions)
    ax.set_yticklabels([f"validate {year}" for year in audit.sort_values("validation_year")["validation_year"]])
    ax.set_xticks(years)
    ax.set_xlim(min(years) - 0.8, max(years) + 2.1)
    ax.set_ylim(-0.7, len(audit) - 0.3)
    ax.invert_yaxis()
    ax.set_xlabel("trajectory year")
    ax.set_title("Figure 13. v2.4 Learned Termination Walk-forward Split")
    ax.grid(False)
    ax.text(
        min(years) - 0.75,
        len(audit) - 0.05,
        "Note: this split shows the offline Ridge termination layer. The cached v2.3 base trajectory was produced with annual model cutoffs.",
        fontsize=8,
        color="#5F6B76",
        ha="left",
        va="bottom",
    )
    return fig, "v24_learned_termination_walk_forward_split"

def figure_14():
    fig, ax = plt.subplots(figsize=(10,4.2))
    ax.axis("off")
    labels = [
        ((0.05,0.62),"Build event plan\nlocations/stages/years","#EAF2F8"),
        ((0.31,0.62),"Collect weather\nfor prediction grid","#FFF2CC"),
        ((0.57,0.62),"Train per cutoff\nand predict trajectories","#FCE4D6"),
        ((0.31,0.22),"Join actual stage dates\ncompute errors","#E2F0D9"),
        ((0.57,0.22),"Summaries\nfigures + tables","#D9EAF7"),
    ]
    for xy, label, color in labels:
        box(ax, xy, label, w=0.20, h=0.18, color=color)
    arrow(ax,(0.25,0.71),(0.31,0.71)); arrow(ax,(0.51,0.71),(0.57,0.71))
    arrow(ax,(0.67,0.62),(0.41,0.40)); arrow(ax,(0.51,0.31),(0.57,0.31))
    ax.set_title("Figure 14. Backtesting Framework Overview")
    return fig, "backtesting_framework_overview"

def figure_15():
    df = read_data("alpha_grid")
    if df.empty:
        df = pd.DataFrame({"ridge_alpha":[30]*6,"theta":[2,3,4,4.5,5,6],"decision_mae":[5.7,5.1,4.6,4.4,4.5,4.8],"decision_rmse":[8.2,7.4,6.8,6.5,6.6,7.0],"reached_rate":[.86,.92,.97,.996,1,1]})
    alpha = 30.0 if 30.0 in set(df["ridge_alpha"]) else df["ridge_alpha"].iloc[0]
    g = df[df["ridge_alpha"] == alpha].sort_values("theta")
    fig, ax = plt.subplots(figsize=(9,4.5))
    ax.plot(g["theta"], g["decision_mae"], marker="o", label="decision MAE", color=COLORS["v2.4"])
    ax.plot(g["theta"], g["decision_rmse"], marker="o", label="decision RMSE", color=COLORS["accent"])
    ax2 = ax.twinx()
    ax2.plot(g["theta"], g["reached_rate"], marker="s", label="reached rate", color=COLORS["v2.3"], alpha=0.8)
    ax.set_xlabel("termination threshold")
    ax.set_ylabel("days")
    ax2.set_ylabel("reached rate")
    ax.set_title("Figure 15. Threshold Sweep for Learned Ridge")
    lines, labels = ax.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax.legend(lines + lines2, labels + labels2, frameon=False)
    return fig, "threshold_sweep_learned_ridge"

def figure_16():
    df = read_data("alpha_grid")
    if df.empty:
        df = pd.DataFrame({"ridge_alpha":[.1,1,10,30,100],"theta":[4.5]*5,"decision_rmse":[7.1,6.9,6.7,6.48,6.50],"decision_mae":[4.9,4.7,4.5,4.36,4.38]})
    g = df.loc[(df["theta"] - 4.5).abs() == (df["theta"] - 4.5).abs().min()].sort_values("ridge_alpha")
    fig, ax = plt.subplots(figsize=(9,4.5))
    ax.plot(g["ridge_alpha"], g["decision_rmse"], marker="o", label="decision RMSE", color=COLORS["accent"])
    ax.plot(g["ridge_alpha"], g["decision_mae"], marker="o", label="decision MAE", color=COLORS["v2.4"])
    ax.set_xscale("log")
    ax.set_xlabel("Ridge alpha")
    ax.set_ylabel("days")
    ax.set_title("Figure 16. Ridge Alpha Grid Search Results")
    ax.legend(frameon=False)
    return fig, "ridge_alpha_grid_search"

def figure_17():
    df = read_data("ablation_summary")
    if df.empty:
        df = pd.DataFrame({"ablation_name":["full_features","no_lag_slope_recent_shape","no_crossing","no_location"],"decision_rmse":[6.47,6.46,7.1,6.8]})
    df = df.copy().sort_values("decision_rmse")
    fig, ax = plt.subplots(figsize=(9,4.5))
    ax.bar(df["ablation_name"].map(clean_label), df["decision_rmse"], color=COLORS["v2.4"])
    ax.set_ylabel("decision RMSE days")
    ax.set_title("Figure 17. Feature Group Ablation Impact on Decision RMSE")
    ax.tick_params(axis="x", rotation=25)
    return fig, "feature_group_ablation_decision_rmse"

def comparison_summary_from_detail():
    df = read_data("baseline_vs_learned", parse_dates=["actual_stage_date", "decision_date"])
    if df.empty:
        return pd.DataFrame({"method":["Rule A","Learned Ridge"],"reached_rate":[.88,.996],"decision_mae":[6.2,4.4],"decision_rmse":[9.1,6.5]})
    out = df.groupby("method").agg(
        reached_rate=("termination_reached", "mean"),
        decision_mae=("abs_decision_error_days", "mean"),
        decision_rmse=("decision_error_days", lambda s: float(np.sqrt(np.nanmean(np.square(s))))),
    ).reset_index()
    return out

def figure_18():
    df = comparison_summary_from_detail()
    fig, ax = plt.subplots(figsize=(8,4.2))
    ax.bar(df["method"].map(clean_label), df["reached_rate"], color=[COLORS["rule"] if "Rule" in m else COLORS["v2.4"] for m in df["method"]])
    ax.set_ylim(0, 1.08)
    ax.set_ylabel("reached rate")
    ax.set_title("Figure 18. Reached Rate Comparison")
    bar_labels(ax, "{:.1%}")
    return fig, "reached_rate_comparison"

def figure_19():
    df = comparison_summary_from_detail()
    fig, ax = plt.subplots(figsize=(8.5,4.2))
    grouped_bar(ax, df["method"].map(clean_label).tolist(), {"MAE": df["decision_mae"].values, "RMSE": df["decision_rmse"].values}, ylabel="days", title="Figure 19. Decision MAE and RMSE Comparison")
    return fig, "decision_mae_rmse_comparison"

def figure_20():
    df = read_data("baseline_vs_learned")
    if df.empty:
        vals = np.random.default_rng(42).normal(0, 6, 220)
    else:
        g = df[df["method"].astype(str).str.contains("Learned", case=False, na=False)]
        vals = g["termination_error_days"].dropna().to_numpy()
    fig, ax = plt.subplots(figsize=(8.5,4.2))
    ax.hist(vals, bins=24, color=COLORS["v2.4"], alpha=0.8)
    ax.axvline(0, color="#333", lw=1)
    ax.set_xlabel("adjusted business-date error days")
    ax.set_ylabel("trajectory count")
    ax.set_title("Figure 20. Adjusted Business-Date Error Distribution for Learned Ridge")
    return fig, "learned_ridge_estimated_error_distribution"

def figure_21():
    df = read_data("baseline_vs_learned")
    if df.empty:
        df = pd.DataFrame({"method":["Rule A"]*100+["Learned Ridge"]*100,"decision_error_days":np.r_[np.random.default_rng(1).normal(1,9,100), np.random.default_rng(2).normal(0,6,100)]})
    methods = df["method"].dropna().unique().tolist()
    data = [df.loc[df["method"] == m, "decision_error_days"].dropna() for m in methods]
    fig, ax = plt.subplots(figsize=(9,4.5))
    ax.boxplot(data, labels=[clean_label(m) for m in methods], patch_artist=True,
               boxprops=dict(facecolor="#D9EAF7"), medianprops=dict(color=COLORS["accent"], lw=2))
    ax.axhline(0, color="#333", lw=1)
    ax.set_ylabel("decision error days")
    ax.set_title("Figure 21. Decision Error Distribution")
    return fig, "decision_error_distribution"

def figure_22():
    df = read_data("trajectory_v23_v24", parse_dates=["prediction_date", "actual_stage_date"])
    if df.empty:
        df = pd.DataFrame({"model_version":["v2.3"]*80+["v2.4"]*80,"abs_stage_date_error_days":np.r_[np.random.default_rng(3).gamma(2,6,80), np.random.default_rng(4).gamma(2,3.8,80)]})
    versions = sorted(df["model_version"].dropna().unique())
    data = [df.loc[df["model_version"] == v, "abs_stage_date_error_days"].dropna() for v in versions]
    fig, ax = plt.subplots(figsize=(8.5,4.2))
    ax.boxplot(data, labels=versions, patch_artist=True,
               boxprops=dict(facecolor="#D9EAF7"), medianprops=dict(color=COLORS["accent"], lw=2))
    ax.set_ylabel("absolute stage-date error days")
    ax.set_title("Figure 22. v2.3 vs v2.4 Absolute Error Distribution")
    return fig, "v23_v24_absolute_error_distribution"

def figure_23():
    df = read_data("summary_overall")
    if df.empty:
        df = pd.DataFrame({"model_version":["v2.3","v2.4"],"within_3d_rate":[.27,.41],"within_5d_rate":[.40,.59]})
    labels = df["model_version"].tolist()
    fig, ax = plt.subplots(figsize=(8.5,4.2))
    grouped_bar(ax, labels, {"within 3d": df["within_3d_rate"].values, "within 5d": df["within_5d_rate"].values}, ylabel="rate", title="Figure 23. Within 3d and Within 5d Accuracy Comparison")
    ax.set_ylim(0, 1)
    bar_labels(ax, "{:.1%}")
    return fig, "within_3d_5d_accuracy_comparison"

def figure_24():
    df = read_data("summary_overall")
    if df.empty:
        df = pd.DataFrame({"model_version":["v2.3","v2.4"],"post_event_positive_rate":[.084,.050]})
    fig, ax = plt.subplots(figsize=(8,4.2))
    ax.bar(df["model_version"], df["post_event_positive_rate"], color=[COLORS.get(v, "#999") for v in df["model_version"]])
    ax.set_ylabel("post-event positive rate")
    ax.set_title("Figure 24. Post-event Positive Rate Comparison")
    ax.set_ylim(0, max(df["post_event_positive_rate"].max()*1.35, .1))
    bar_labels(ax, "{:.1%}")
    return fig, "post_event_positive_rate_comparison"

def pick_improvement_trajectory(df, n=1):
    group_cols = ["test_year", "location_id", "stage_id"]
    agg = df.groupby(["model_version"] + group_cols)["abs_stage_date_error_days"].mean().reset_index()
    piv = agg.pivot_table(index=group_cols, columns="model_version", values="abs_stage_date_error_days")
    if {"v2.3", "v2.4"}.issubset(piv.columns):
        piv["improvement"] = piv["v2.3"] - piv["v2.4"]
        keys = piv.sort_values("improvement", ascending=False).head(n).index.tolist()
        return keys
    return df[group_cols].drop_duplicates().head(n).itertuples(index=False, name=None)

def plot_trajectory_group(ax, df, key):
    year, loc, stage = key
    g = df[(df["test_year"].astype(str)==str(year)) & (df["location_id"].astype(str)==str(loc)) & (df["stage_id"].astype(str)==str(stage))].copy()
    for version, part in g.groupby("model_version"):
        part = part.sort_values("prediction_date")
        ax.plot(part["prediction_date"], part["predicted_days"], marker="o", ms=3, label=version, color=COLORS.get(version, None))
    actuals = g["actual_stage_date"].dropna()
    if not actuals.empty:
        ax.axvline(actuals.iloc[0], color=COLORS["accent"], lw=1.5, ls="--", label="actual")
    ax.set_title(f"year={year}, loc={loc}, stage={stage}", fontsize=10)
    ax.set_ylabel("predicted days")
    ax.tick_params(axis="x", rotation=25)

def figure_25():
    df = read_data("trajectory_v23_v24", parse_dates=["prediction_date","actual_stage_date"])
    if df.empty:
        dates = pd.date_range("2025-04-01", periods=16, freq="3D")
        df = pd.DataFrame({
            "test_year":[2025]*32, "location_id":["example"]*32, "stage_id":[1]*32,
            "prediction_date":list(dates)*2, "actual_stage_date":[pd.Timestamp("2025-05-10")]*32,
            "model_version":["v2.3"]*16+["v2.4"]*16,
            "predicted_days":list(np.maximum(25-np.arange(16)*2 + np.sin(np.arange(16))*5,0))+list(np.maximum(25-np.arange(16)*2.2,0)),
            "abs_stage_date_error_days":[5]*32,
        })
    key = list(pick_improvement_trajectory(df, 1))[0]
    fig, ax = plt.subplots(figsize=(9.5,4.6))
    plot_trajectory_group(ax, df, key)
    ax.set_title("Figure 25. Bounce-back Case Study Trajectories\n" + ax.get_title())
    ax.legend(frameon=False)
    return fig, "bounce_back_case_study_trajectory"

def figure_26():
    df = read_data("summary_year_stage")
    if df.empty:
        df = pd.DataFrame({"model_version":["v2.3","v2.4"]*3,"stage_id":[1,1,2,2,3,3],"mae_stage_date_error":[12,7,10,6,13,8]})
    piv = df.groupby(["stage_id","model_version"])["mae_stage_date_error"].mean().unstack()
    if {"v2.3","v2.4"}.issubset(piv.columns):
        improvement = piv["v2.3"] - piv["v2.4"]
    else:
        improvement = piv.iloc[:,0]
    fig, ax = plt.subplots(figsize=(8,4.2))
    ax.bar([f"stage {s}" for s in improvement.index], improvement.values, color=COLORS["v2.4"])
    ax.axhline(0, color="#333", lw=1)
    ax.set_ylabel("MAE improvement days\npositive means v2.4 better")
    ax.set_title("Figure 26. Stage-level MAE Improvement")
    bar_labels(ax, "{:.1f}")
    return fig, "stage_level_mae_improvement"

def figure_27():
    df = read_data("summary_year_stage")
    if df.empty:
        df = pd.DataFrame({"model_version":["v2.3","v2.4"]*4,"test_year":[2022,2022,2023,2023,2024,2024,2025,2025],"mae_stage_date_error":[12,8,13,7,11,6,10,6],"rmse_stage_date_error":[17,11,18,10,15,9,14,8]})
    g = df.groupby(["test_year","model_version"])[["mae_stage_date_error","rmse_stage_date_error"]].mean().reset_index()
    fig, axes = plt.subplots(1,2, figsize=(11,4.2), sharey=False)
    for ax, metric, title in zip(axes, ["mae_stage_date_error","rmse_stage_date_error"], ["MAE", "RMSE"]):
        piv = g.pivot(index="test_year", columns="model_version", values=metric)
        grouped_bar(ax, [str(x) for x in piv.index], {c: piv[c].values for c in piv.columns}, ylabel="days", title=title)
    fig.suptitle("Figure 27. Year-level MAE / RMSE Comparison", y=1.03)
    return fig, "year_level_mae_rmse_comparison"

def figure_28():
    df = read_data("trajectory_v23_v24", parse_dates=["prediction_date","actual_stage_date"])
    if df.empty:
        rng = np.random.default_rng(5)
        df = pd.DataFrame({"model_version":np.repeat(["v2.3","v2.4"],100),"actual_latitude":np.r_[rng.uniform(36,45,100), rng.uniform(36,45,100)],"abs_stage_date_error_days":np.r_[rng.gamma(2,5,100), rng.gamma(2,3.2,100)]})
    lat_col = "actual_latitude" if "actual_latitude" in df.columns else "latitude"
    plot_df = df.dropna(subset=[lat_col, "abs_stage_date_error_days"]).copy()
    plot_df["latitude_band"] = pd.cut(plot_df[lat_col], bins=5)
    g = plot_df.groupby(["latitude_band","model_version"])["abs_stage_date_error_days"].mean().reset_index()
    piv = g.pivot(index="latitude_band", columns="model_version", values="abs_stage_date_error_days").fillna(0)
    fig, ax = plt.subplots(figsize=(10,4.5))
    labels = [f"{iv.left:.1f}-{iv.right:.1f}" for iv in piv.index]
    grouped_bar(ax, labels, {c: piv[c].values for c in piv.columns}, ylabel="mean abs error days", title="Figure 28. Latitude-band Error Plot")
    ax.set_xlabel("latitude band")
    return fig, "latitude_band_error_plot"

def figure_29():
    df = read_data("trajectory_v23_v24", parse_dates=["prediction_date","actual_stage_date"])
    if df.empty:
        return figure_25()
    keys = list(pick_improvement_trajectory(df, 4))
    fig, axes = plt.subplots(2,2, figsize=(12,7), sharey=True)
    for ax, key in zip(axes.ravel(), keys):
        plot_trajectory_group(ax, df, key)
    handles, labels = axes.ravel()[0].get_legend_handles_labels()
    fig.legend(handles, labels, frameon=False, loc="upper center", ncol=4)
    fig.suptitle("Figure 29. Representative Trajectory Case Studies", y=1.02)
    fig.tight_layout()
    return fig, "representative_trajectory_case_studies"

def figure_30():
    fig, ax = plt.subplots(figsize=(10,5))
    ax.axis("off")
    items = [
        ((0.05,0.70), "Input row\nweather + stage", "#EAF2F8"),
        ((0.32,0.70), "LightGBM\npredict", "#FCE4D6"),
        ((0.58,0.70), "termination_model\nenabled?", "#FFF2CC"),
        ((0.32,0.25), "No: output\nbase prediction", "#F4F6F6"),
        ((0.78,0.70), "Load Ridge\nmodel", "#E2F0D9"),
        ((0.78,0.36), "Subtract\nthreshold", "#FFF2CC"),
        ((0.58,0.10), "Preserve raw\ndiagnostics", "#F4F6F6"),
        ((0.88,0.10), "Output adjusted\nremaining curve", "#D9EAD3"),
    ]
    for xy, label, color in items:
        box(ax, xy, label, w=0.17, h=0.15, color=color)
    arrow(ax,(0.22,0.78),(0.32,0.78)); arrow(ax,(0.49,0.78),(0.58,0.78))
    arrow(ax,(0.63,0.70),(0.41,0.40)); ax.text(0.48,0.48,"False", fontsize=9)
    arrow(ax,(0.75,0.78),(0.78,0.78)); ax.text(0.74,0.83,"True", fontsize=9)
    arrow(ax,(0.865,0.70),(0.865,0.51)); arrow(ax,(0.78,0.40),(0.66,0.25)); arrow(ax,(0.90,0.36),(0.93,0.25))
    ax.text(0.71,0.27,"False", fontsize=9); ax.text(0.92,0.27,"True", fontsize=9)
    ax.set_title("Figure 30. Production Runtime Decision Tree")
    return fig, "production_runtime_decision_tree"

def figure_31():
    fig, ax = plt.subplots(figsize=(11,6))
    ax.axis("off")
    panels = [
        ((0.04,0.68),0.28,0.22,"Model health\nMAE, RMSE, P90"),
        ((0.36,0.68),0.28,0.22,"Termination monitoring\ntrigger rate, early/late"),
        ((0.68,0.68),0.28,0.22,"Post-event behavior\npositive rate, bounce-back"),
        ((0.04,0.36),0.44,0.22,"Stage-level drilldown\nstage 1 / 2 / 3 metrics"),
        ((0.52,0.36),0.44,0.22,"Geography\nregion and latitude-band drift"),
        ((0.04,0.08),0.92,0.18,"Alert feed\nthreshold breach, data gaps, unusual prediction-date drift"),
    ]
    for (xy,w,h,label) in panels:
        patch = FancyBboxPatch(xy, w, h, boxstyle="round,pad=0.02,rounding_size=0.025",
                               facecolor="#F7F9FB", edgecolor="#8091A5", linewidth=1.2)
        ax.add_patch(patch)
        ax.text(xy[0]+0.02, xy[1]+h-0.05, label, ha="left", va="top", weight="bold")
        for i in range(3):
            ax.add_patch(Rectangle((xy[0]+0.03, xy[1]+0.04+i*0.04), w-0.06, 0.015,
                                   facecolor=[COLORS["v2.4"], COLORS["v2.3"], COLORS["muted"]][i%3], alpha=0.65))
    ax.set_xlim(0,1); ax.set_ylim(0,1)
    ax.set_title("Figure 31. Proposed Production Monitoring Dashboard Layout")
    return fig, "production_monitoring_dashboard_layout"

FIGURE_RENDERERS = {i: globals()[f"figure_{i}"] for i in range(1, 32)}
TABLE_RENDERERS = {i: globals()[f"table_{i}"] for i in range(1, 17)}

def render_figure(number):
    fig, slug = FIGURE_RENDERERS[number]()
    return save_and_show(fig, number, slug)

def render_table(number):
    df, slug = TABLE_RENDERERS[number]()
    return save_table(df, number, slug)

print(f"Project root: {ROOT}")
print(f"Figures and tables will be saved to: {OUT_DIR.relative_to(ROOT)}")
'''


def markdown_cell(source: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source.splitlines(True)}


def code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source.splitlines(True),
    }


def build_notebook() -> dict:
    table_captions = {
        1: "Executive Summary Metrics，列出 v2.3 vs v2.4 的核心指标。",
        2: "Model Evolution Summary，总结 v2.1 到 v2.4 的模型路线和主要限制。",
        3: "v2.4 Output Columns and Definitions，定义 learned termination 相关输出字段。",
        4: "Primary LightGBM Feature List，列出 v2.4 主模型输入特征和单调约束。",
        5: "Rule A vs Rule B Comparison，对比固定 termination 规则和 learned Ridge 的设计差异。",
        6: "Learned Termination Configuration，列出 v2.4 YAML 中 termination_model 参数。",
        7: "Static and Contextual Termination Features，总结 learned termination 的上下文和轨迹特征组。",
        8: "v2.4 Prediction Output Schema，总结生产预测输出字段。",
        9: "v2.4 Unit Test Inventory，列出 v2.4 相关测试覆盖。",
        10: "Evaluation Metrics Definition Table，定义 whitepaper 中使用的评估指标。",
        11: "Rule-based Termination Baseline Results，展示 rule-based baseline 的终止误差结果。",
        12: "Final Learned Termination Model Selection Summary，总结最终 learned termination 选择。",
        13: "v2.3 vs v2.4 Overall Forecast Accuracy，汇总 end-to-end 整体精度。",
        14: "Stage-level v2.3 vs v2.4 Performance Summary，按 stage 汇总 v2.3/v2.4 表现。",
        15: "Core Implementation Functions and Responsibilities，列出核心实现文件和职责。",
        16: "Risk Register and Mitigation Plan，列出治理风险和缓解策略。",
    }
    figure_captions = {
        1: "WeevilTrak Prediction Task Diagram，展示从 weather + location + stage 到 predicted_days / predicted_stage_date 的业务流程。",
        2: "Example v2.3 Failure Trajectory，展示典型 v2.3 trajectory、actual stage date、post-event positive area 和 bounce-back segment。",
        3: "Version Evolution Timeline，展示 v2.1 到 v2.4 每个版本解决的问题。",
        4: "v2.4 End-to-End Architecture Diagram，展示 LightGBM 主模型和 Ridge termination layer 的上下游关系。",
        5: "Zero-day Error Concept Diagram，展示 early / exact / late / not reached 四种情况。",
        6: "v2.2 vs v2.3 Zero-day Error Distribution，用 boxplot 对比 zero-day error。",
        7: "Learned Termination Decision Flowchart，展示 learned Ridge termination 的触发逻辑。",
        8: "Trajectory Signal, Lag and Slope Illustration，展示 trajectory 上 lag 和 slope 的含义。",
        9: "Rolling Linear and Spline Crossing Illustration，展示 trajectory、linear fit、spline proxy、0 crossing 和 -0.5 crossing。",
        10: "Feature Ablation Results，展示移除不同 feature group 后的 decision MAE 变化。",
        11: "Training Pipeline for v2.4，展示 LightGBM training 到 Ridge training 的训练链路。",
        12: "Online Inference Flow Diagram，展示线上预测和 learned termination 的推理链路。",
        13: "Walk-forward Validation Split by Year，展示按年份前向验证的 train/test 切分。",
        14: "Backtesting Framework Overview，展示 backtesting plan、weather、prediction 和 evaluation 的关系。",
        15: "Threshold Sweep for Learned Ridge，展示 threshold 对 decision MAE/RMSE/reached rate 的影响。",
        16: "Ridge Alpha Grid Search Results，展示 Ridge alpha 对 decision error 的影响。",
        17: "Feature Group Ablation Impact on Decision RMSE，展示 feature group 对 decision RMSE 的影响。",
        18: "Reached Rate Comparison，对比 rule-based baseline 和 learned Ridge 的 reached rate。",
        19: "Decision MAE and RMSE Comparison，对比 baseline 和 learned Ridge 的 decision MAE/RMSE。",
        20: "Adjusted Business-Date Error Distribution for Learned Ridge，展示 learned Ridge adjusted business-date error 分布。",
        21: "Decision Error Distribution，对比 baseline 和 learned Ridge 的 decision error 分布。",
        22: "v2.3 vs v2.4 Absolute Error Distribution，展示 end-to-end absolute stage-date error 分布。",
        23: "Within 3d and Within 5d Accuracy Comparison，对比 v2.3 和 v2.4 的近窗口命中率。",
        24: "Post-event Positive Rate Comparison，对比 v2.3 和 v2.4 event 后正值预测率。",
        25: "Bounce-back Case Study Trajectories，展示一个实际 event 附近的 v2.3 / v2.4 trajectory。",
        26: "Stage-level MAE Improvement，展示每个 stage 的 v2.4 MAE 改善。",
        27: "Year-level MAE / RMSE Comparison，按年份对比 v2.3 和 v2.4 的 MAE/RMSE。",
        28: "Location-level Error Map or Latitude-band Error Plot，用 latitude band 展示空间误差差异。",
        29: "Representative Trajectory Case Studies，展示多个代表性 trajectory case。",
        30: "Production Runtime Decision Tree，展示 production runtime 是否触发 termination 的决策树。",
        31: "Proposed Production Monitoring Dashboard Layout，展示推荐的生产监控 dashboard 布局。",
    }
    report_items = [
        ("table", 1),
        ("figure", 1),
        ("figure", 2),
        ("table", 2),
        ("figure", 3),
        ("figure", 4),
        ("table", 3),
        ("table", 4),
        ("figure", 5),
        ("figure", 6),
        ("table", 5),
        ("table", 6),
        ("figure", 7),
        ("table", 7),
        ("figure", 8),
        ("figure", 9),
        ("figure", 10),
        ("figure", 11),
        ("figure", 12),
        ("table", 8),
        ("figure", 13),
        ("table", 9),
        ("figure", 14),
        ("table", 10),
        ("table", 11),
        ("figure", 15),
        ("figure", 16),
        ("figure", 17),
        ("table", 12),
        ("figure", 18),
        ("figure", 19),
        ("figure", 20),
        ("figure", 21),
        ("table", 13),
        ("figure", 22),
        ("figure", 23),
        ("figure", 24),
        ("figure", 25),
        ("table", 14),
        ("figure", 26),
        ("figure", 27),
        ("figure", 28),
        ("figure", 29),
        ("table", 15),
        ("figure", 30),
        ("table", 16),
        ("figure", 31),
    ]

    cells: list[dict] = [
        markdown_cell(
            "# WeevilTrak v2.4 Report Tables and Figures\n\n"
            "This notebook renders the numbered tables and figures from the full `v2.4 Report.docx` outline.\n\n"
            "Run all cells to regenerate Table 1 through Table 16 and Figure 1 through Figure 31. Outputs are saved under `outputs/report_figures/v2_4/`."
        ),
        code_cell(SETUP_CODE),
    ]
    for kind, number in report_items:
        if kind == "table":
            cells.append(markdown_cell(f"## Table {number}: {table_captions[number]}\n"))
            cells.append(code_cell(f"render_table({number})\n"))
        else:
            cells.append(markdown_cell(f"## Figure {number}: {figure_captions[number]}\n"))
            cells.append(code_cell(f"render_figure({number})\n"))

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "pygments_lexer": "ipython3",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def main() -> None:
    NOTEBOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
    NOTEBOOK_PATH.write_text(
        json.dumps(build_notebook(), ensure_ascii=False, indent=1) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {NOTEBOOK_PATH}")


if __name__ == "__main__":
    main()
